remote_theme: jekyll-theme-minimal
markdown: GFM
title: R for single-cell
description: <h3>Introduction to R for genomics</h3>  <figure><img src="./TRR179.png"></figure><h4>Carl Herrmann & Carlos Ramirez</h4>8-9 December 2021 
